####################
# Coded By SaschaG #
####################
messages:
  prefix: "&6Tablist &8>&r "
  nopermission: "%prefix% &cDazu hast du keine Rechte"
config:
  autoUpdate: false
  updatePerSeconds: 15
permissions:
  permission*: tablist.*
  createGroup: tablist.create
  removeGroup: tablist.remove
  reload: tablist.reload
  save: tablist.save
  editGroup: tablist.edit
  list: tablist.list
  info: tablist.info
groups:



